name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job 1: Test and Check the Code (CI)
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: HTML Validation Check
        uses: cyb3rjacob/html5validator-action@v1.1.0
        with:
          root: '.'

  # Job 2: Deploy to Server (CD) - Only runs if Job 1 passes!
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
