name: Deploy Website to Render Server

on:
  push:
    branches:
      - main

jobs:
  # Stage 1: Continuous Integration (CI) - Code Testing
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check HTML Integrity
        uses: cyb3rjacob/html5validator-action@v1.1.0
        with:
          root: '.'

  # Stage 2: Continuous Deployment (CD) - Live Push to Render Server
  deploy_to_render:
    needs: test_code
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Server Update
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"